### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by yashbhalgat** [HengyiWang/neural-rgbd-torch#1]
Hi @HengyiWang, thanks for releasing a Pytorch implementation!

I tried out running the code with the default hyperparameters as: `python optimize.py --config configs/morning_apartment.txt`, but I get a Out Of Memory error.

I tried different GPUs with 12GB, 24GB and 48GB memory. And it throws the same error. 

Everytime, this error occurs at iteration number `4999`.

Can you please advise what might be happening?

**Comment by HengyiWang** [comment]
Hello @yashbhalgat, thanks for using the code. For the memory issue, it should be caused by the full resolution rendering of the image, you could change the render_factor in the morning_apartment.txt from 1 to maybe 10 and it should be working.

Note that if you want a full resolution rendering, just add something like a batchtify in the get_logging_image function.

Good luck with your experiments!

**Comment by yashbhalgat** [comment]
Hi @HengyiWang , thanks for the quick response.

The `get_logging_image` calls the `render` function which already uses `batchify_rays`, right? So, shouldn't that already handle the rendering with `args.chunk`?

Also, `i_img=500` in my case. So, the `get_logging_image` function is called every 500 iterations, but the OOM error appears only at 4999 iterations every time. I am not sure what happens at this particular iteration.

**Comment by HengyiWang** [comment]
Hi @yashbhalgat, thanks for reporting this. I have fixed the rendering issue and tested it on both google colab and Tesla V100, it should be working now :-)

**Comment by yashbhalgat** [comment]
Thanks for the elegant fix (`with torch.no_grad():`) @HengyiWang! I will try the latest code on my side too :) 

Update: I think this has fixed the problem.
